export const fields = {
  name: { 
    type: 'link', 
    label: 'Nombre',
    url: (record) => `/service/detail/${record._id}`,
  },
  cupsCode: { type: 'string', label: 'Código CUPS' },
  simonLevel: {
    type: 'string',
    label: 'Código SIMON',
  },
  aliases: { type: 'array', label: 'Alias', options: [] },
  description: { type: 'textarea', label: 'Descripción' },
  category: {
    type: 'selectWithTranslation',
    options: [
      { value: 'consulta', label: 'Consulta', color: 'blue' },
      { value: 'procedimiento', label: 'Procedimiento', color: 'purple' },
      { value: 'visita_domicilio', label: 'Visita domicilio', color: 'green' },
      { value: 'estudio', label: 'Estudio', color: 'cyan' },
      { value: 'otro', label: 'Otro', color: 'gray' },
    ],
    renderAsTag: true,
    label: 'Categoría',
  },
  type: {
    type: 'selectWithTranslation',
    options: [
      { value: 'primera_vez', label: 'Primera vez', color: 'blue' },
      { value: 'seguimiento', label: 'Seguimiento', color: 'green' },
      { value: 'urgencia', label: 'Urgencia', color: 'red' },
      { value: 'visita_domicilio', label: 'Visita domicilio', color: 'orange' },
      { value: 'procedimiento', label: 'Procedimiento', color: 'purple' },
      { value: 'otro', label: 'Otro', color: 'gray' },
    ],
    renderAsTag: true,
    label: 'Tipo',
  },
  modalidad: {
    type: 'selectWithTranslation',
    options: [
      { value: 'clinica', label: 'Clínica', color: 'blue' },
      { value: 'domicilio', label: 'Domicilio', color: 'green' },
      { value: 'telemedicina', label: 'Telemedicina', color: 'cyan' },
    ],
    renderAsTag: true,
    label: 'Modalidad',
  },
  tipoServicio: {
    type: 'selectWithTranslation',
    options: [
      { value: 'consulta', label: 'Consulta', color: 'blue' },
      { value: 'procedimiento', label: 'Procedimiento', color: 'purple' },
      { value: 'diagnostico', label: 'Diagnóstico', color: 'cyan' },
      { value: 'enfermeria', label: 'Enfermería', color: 'green' },
      { value: 'hospitalizacion_domiciliaria', label: 'Hospitalización domiciliaria', color: 'orange' },
      { value: 'programa_especial', label: 'Programa especial', color: 'magenta' },
    ],
    renderAsTag: true,
    label: 'Tipo de servicio',
  },
  clasificacion: {
    type: 'multiSelect',
    options: [
      { value: 'clinico', label: 'Clínico', color: 'blue' },
      { value: 'administrativo', label: 'Administrativo', color: 'gray' },
      { value: 'diagnostico', label: 'Diagnóstico', color: 'cyan' },
      { value: 'terapeutico', label: 'Terapéutico', color: 'green' },
      { value: 'preventivo', label: 'Preventivo', color: 'gold' },
      { value: 'domiciliario', label: 'Domiciliario', color: 'green' },
      { value: 'hospitalario', label: 'Hospitalario', color: 'red' },
      { value: 'ambulatorio', label: 'Ambulatorio', color: 'geekblue' },
      { value: 'empresarial', label: 'Empresarial', color: 'purple' },
      { value: 'telemedicina', label: 'Telemedicina', color: 'cyan' },
    ],
    renderAsTag: true,
    label: 'Clasificación',
  },
  grupoCatalogo: {
    type: 'selectWithTranslation',
    options: [
      { value: 'consultas_medicas', label: 'Consultas médicas', color: 'blue' },
      { value: 'medicina_dolor', label: 'Medicina del dolor', color: 'purple' },
      { value: 'procedimientos_intervencionistas', label: 'Procedimientos intervencionistas', color: 'magenta' },
      { value: 'cuidados_paliativos', label: 'Cuidados paliativos', color: 'gold' },
      { value: 'enfermeria', label: 'Enfermería', color: 'green' },
      { value: 'rayos_x', label: 'Rayos X', color: 'cyan' },
      { value: 'sonografia', label: 'Sonografía/Ecografía', color: 'geekblue' },
      { value: 'doppler_vascular', label: 'Doppler vascular', color: 'red' },
      { value: 'estudios_cardiacos', label: 'Estudios cardíacos', color: 'orange' },
      { value: 'laboratorio', label: 'Laboratorio clínico', color: 'lime' },
      { value: 'hospitalizacion_domiciliaria', label: 'Hospitalización domiciliaria', color: 'volcano' },
      { value: 'hemohogar', label: 'Hemohogar®', color: 'red' },
      { value: 'oncomejorate', label: 'Oncomejórate', color: 'purple' },
      { value: 'terapias', label: 'Terapias', color: 'green' },
      { value: 'programas_especiales', label: 'Programas especiales', color: 'magenta' },
      { value: 'programas_empresariales', label: 'Programas empresariales', color: 'blue' },
      { value: 'sin_clasificar', label: 'Sin clasificar', color: 'gray' },
    ],
    renderAsTag: true,
    label: 'Grupo del catálogo',
  },
  preguntasCotizacion: {
    type: 'tags',
    options: [],
    label: 'Preguntas para cotizar',
  },
  materiales: {
    type: 'tags',
    options: [],
    label: 'Materiales',
  },
  personalRequerido: {
    type: 'tags',
    options: [],
    label: 'Personal requerido',
  },
  prioridadDefault: {
    type: 'selectWithTranslation',
    options: [
      { value: 'emergente', label: 'Emergente', color: 'red' },
      { value: 'urgente', label: 'Urgente', color: 'orange' },
      { value: 'preferente', label: 'Preferente', color: 'gold' },
      { value: 'programado', label: 'Programado', color: 'green' },
    ],
    renderAsTag: true,
    label: 'Prioridad',
  },
  basePrice: { type: 'currency', label: 'Precio base' },
  isActive: { type: 'boolean', label: 'Activo' },
};
