[phases.setup]
nixPkgs = ["nodejs_20", "git", "pnpm"]

[phases.install]
cmds = ["cd apps/crm/frontend && pnpm install && pnpm run build && cd ../backend && pnpm install"]

[start]
cmd = "cd apps/crm/backend && node src/server.js"
